# Generated by Django 3.2.4 on 2021-06-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illness',
            old_name='illness_name',
            new_name='illnessname',
        ),
    ]
