# Generated by Django 3.2.4 on 2021-06-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_illness_name_illness_illnessname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illness',
            old_name='recommndations',
            new_name='recommendation',
        ),
    ]
