# Generated by Django 3.2.4 on 2021-06-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_drug_overcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
